import { IUser } from '@/api/type';

export const users: IUser[] = [
  {
    Nom: 'yahya',
    Ville: 'casa',
    Telephone: 'isocked.com',
    Sujet: 'Yahya',
    Email: 'Developer',
    Type: 'China',
    Activité: '(+86) 4567-8900',
    status: 'active',
  },
  {
    Nom: 'yahya',
    Ville: 'casa',
    Telephone: 'isocked.com',
    Sujet: 'Yahya',
    Email: 'Developer',
    Type: 'China',
    Activité: '(+86) 4567-8900',
    status: 'active',
  },
  {
    Nom: 'yahya',
    Ville: 'casa',
    Telephone: 'isocked.com',
    Sujet: 'Yahya',
    Email: 'Developer',
    Type: 'China',
    Activité: '(+86) 4567-8900',
    status: 'active',
  },
  {
    Nom: 'yahya',
    Ville: 'casa',
    Telephone: 'isocked.com',
    Sujet: 'Yahya',
    Email: 'Developer',
    Type: 'China',
    Activité: '(+86) 4567-8900',
    status: 'active',
  },
  {
    Nom: 'yahya',
    Ville: 'casa',
    Telephone: 'isocked.com',
    Sujet: 'Yahya',
    Email: 'Developer',
    Type: 'China',
    Activité: '(+86) 4567-8900',
    status: 'active',
  },
  {
    Nom: 'yahya',
    Ville: 'casa',
    Telephone: 'isocked.com',
    Sujet: 'Yahya',
    Email: 'Developer',
    Type: 'China',
    Activité: '(+86) 4567-8900',
    status: 'active',
  },
  {
    Nom: 'yahya',
    Ville: 'casa',
    Telephone: 'isocked.com',
    Sujet: 'Yahya',
    Email: 'Developer',
    Type: 'China',
    Activité: '(+86) 4567-8900',
    status: 'active',
  },
  {
    Nom: 'yahya',
    Ville: 'casa',
    Telephone: 'isocked.com',
    Sujet: 'Yahya',
    Email: 'Developer',
    Type: 'China',
    Activité: '(+86) 4567-8900',
    status: 'active',
  },
  {
    Nom: 'yahya',
    Ville: 'casa',
    Telephone: 'isocked.com',
    Sujet: 'Yahya',
    Email: 'Developer',
    Type: 'China',
    Activité: '(+86) 4567-8900',
    status: 'active',
  },
  {
    Nom: 'yahya',
    Ville: 'casa',
    Telephone: 'isocked.com',
    Sujet: 'Yahya',
    Email: 'Developer',
    Type: 'China',
    Activité: '(+86) 4567-8900',
    status: 'active',
  },
  {
    Nom: 'yahya',
    Ville: 'casa',
    Telephone: 'isocked.com',
    Sujet: 'Yahya',
    Email: 'Developer',
    Type: 'China',
    Activité: '(+86) 4567-8900',
    status: 'active',
  },
  {
    Nom: 'yahya',
    Ville: 'casa',
    Telephone: 'isocked.com',
    Sujet: 'Yahya',
    Email: 'Developer',
    Type: 'China',
    Activité: '(+86) 4567-8900',
    status: 'active',
  },
  {
    Nom: 'yahya',
    Ville: 'casa',
    Telephone: 'isocked.com',
    Sujet: 'Yahya',
    Email: 'Developer',
    Type: 'China',
    Activité: '(+86) 4567-8900',
    status: 'active',
  }


];

